<?php

namespace Vinv\SigproBundle\Entity;


/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UseridRepository {

    public function getUser($credentials) {
        $em = $this->getDoctrine()->getManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("SELECT * FROM dbo.userID where login = :username and password = :password LIMIT 1");

        $statement->execute(array('username' => $credentials->username, 'password' => $credentials->password));
        
        $results = $statement->fetchAll();
        return $results;
        
    }

}
